### ISSUE TITLE
Font & font styles not enqueued

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-mins-theme#38]
Migrated from Primer:
https://github.com/godaddy/wp-primer-theme/issues/213

Copied from WordPress.org support forums:
https://wordpress.org/support/topic/font-issue-conflict-with-beaver-builder-lite-mins-child-theme/

I originally posted about this issue in the Beaver Builder Lite thread: here

I am using Mins 1.1.0. I recently upgraded Beaver Builder Lite to 1.10.4, and again to 1.10.5.1. The problem persisted through both updates. “Open Sans” was selected as my font in every drop-down option available (except for one) in the “Customize” menu, but what was displaying was a bold, almost Arial-like sans serif font. The paragraph font, instead of Open Sans, was displaying in some sort of Times-looking serif.

I noticed the “Secondary” font was selected as “Droid Sans.” When I changed this to “Open Sans,” everything on the home page corrected, but the other pages kept the Arial and Times-looking fonts.

Here is the response I got from a Beaver Builder dev:

The issue is with the theme you’re using. I’m not really sure why but it’s adding a bunch of styling only on your homepage, not on any other pages. Check the screenshot below for reference.
http://imgur.com/a/mB88R

He told me to add this CSS code in, and this fixed the problem:

```css
.site-title{font-family:"Open Sans", sans-serif;}
.main-navigation ul li a,.main-navigation ul li a:visited,button,a.button,a.fl-button,input[type="button"],input[type="reset"],input[type="submit"]{font-family:"Open Sans", sans-serif;}
h1,h2,h3,h4,h5,h6,label,legend,table th,dl dt,.entry-title,.widget-title{font-family:"Open Sans", sans-serif;}
body,p,ol li,ul li,dl dd,.fl-callout-text{font-family:"Open Sans", sans-serif;}
blockquote,.entry-meta,.entry-footer,.comment-list li .comment-meta .says,.comment-list li .comment-metadata,.comment-reply-link,#respond .logged-in-as{font-family:"Open Sans", sans-serif;}
```

So my problem at the moment is resolved, but I wanted to let you guys know in case you wanted to investigate this further.

It’s fixed on my staging site too, but in case you need to investigate you can find it here:http://d35.9df.myftpupload.com/
