### ISSUE TITLE
Change header colour

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-mins-theme#44]
Hi,

Does anyone know how to change the header colours on this page from green to white without affecting other pages on the website?

http://andyvidlerwildlifephotography.co.uk/trips/

Thanks,

Mark

**Comment by EvanHerman** [comment]
If you want to just change the color of the title on that page only, you can try the following:

```css
body.page-id-621 .fl-callout-title a {
    color: white;
}
```
