### ISSUE TITLE
Custom CSS for hero button

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-mins-theme#63]
Hi,

Can anyone suggest some CSS to add a background colour to my hero button and also change the text colour? http://i4h.251.myftpupload.com

Many thanks,
Mark

**Comment by EvanHerman** [comment]
Hi @markvidler84 

You can change the background color of the hero button with the following css:

```css
.hero .hero-inner a.button {
    background: red !important;
    padding: 10px;
    color: white;
}
```

Otherwise I would recommend setting the button color from within the customizer.

The `!important` tag is required because there are other styles overriding custom styles.
